### ISSUE TITLE
Adopt new Maven Archetype from Adobe

### ISSUE THREAD

**Issue by tomaszsoczyk-cognifide** [Cognifide/aem-project-archetype#10]
### Expected Behaviour
Archetype should be based on latest version of Adobe's archetype (v23)
### Actual Behaviour
This archetype currently is based on v23

**Comment by pun-ky** [comment]
it is based on even 24 ;)   
  
 

![](https://user-images.githubusercontent.com/10673561/95958836-01ed8980-0e02-11eb-8992-f58475bb4152.png)
